In [28]:
import pandas as pd
import os

In [29]:
onet = pd.read_csv("C:\\Users\\bhatt\\OneDrive\\Desktop\\LUCIDEX\\Job Parser\\data\\software_skills.csv")
print(f"shape:{onet.shape}")
print(onet.columns.tolist())

shape:(31821, 7)
['O*NET-SOC Code', 'Title', 'Workplace Example', 'Element ID', 'Element Name', 'Hot Technology', 'In Demand']

In [60]:
onet

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,2.E.5.b,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,2.E.6.f,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,2.E.5.a,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,2.E.6.c,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,2.E.2.a,Accounting software,N,N
...,...,...,...,...,...,...,...
31816,53-7121.00,"Tank Car, Truck, and Ship Loaders",Linux,2.E.13.c,Operating system software,Y,N
31817,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Excel,2.E.4.i,Spreadsheet software,Y,N
31818,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Office software,2.E.1.k,Office suite software,Y,N
31819,53-7121.00,"Tank Car, Truck, and Ship Loaders",SAP software,2.E.2.b,Enterprise resource planning ERP software,Y,N
31820,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse management system WMS,2.E.1.d,Materials requirements planning logistics and ...,N,Y

In [30]:
onet['Title'].head(10)

0    Chief Executives
1    Chief Executives
2    Chief Executives
3    Chief Executives
4    Chief Executives
5    Chief Executives
6    Chief Executives
7    Chief Executives
8    Chief Executives
9    Chief Executives
Name: Title, dtype: str

In [31]:
print("Unique job titles", onet['Title'].nunique())
print("Unique Skills", onet['Element ID'].nunique())

print("Sample Job titles")
print(onet['Title'].drop_duplicates().head(20).to_list())
print("Sample Skills")
print(onet['Element Name'].drop_duplicates().head(20).to_list())
print("Hot Technologies")
print(onet['Hot Technology'].value_counts())
print("In Demand")
print(onet['In Demand'].value_counts())

Unique job titles 923
Unique Skills 134
Sample Job titles
['Chief Executives', 'Chief Sustainability Officers', 'General and Operations Managers', 'Legislators', 'Advertising and Promotions Managers', 'Marketing Managers', 'Sales Managers', 'Public Relations Managers', 'Fundraising Managers', 'Administrative Services Managers', 'Facilities Managers', 'Security Managers', 'Computer and Information Systems Managers', 'Financial Managers', 'Treasurers and Controllers', 'Investment Fund Managers', 'Industrial Production Managers', 'Quality Control Systems Managers', 'Geothermal Production Managers', 'Biofuels Production Managers']
Sample Skills
['Document management software', 'Data base user interface and query software', 'Content workflow software', 'Customer relationship management CRM software', 'Accounting software', 'Data base reporting software', 'Electronic mail software', 'Time accounting software', 'Enterprise application integration software', 'Graphics or photo imaging software', 'Human resources software', 'Project management software', 'Analytical or scientific software', 'Presentation software', 'Enterprise resource planning ERP software', 'Spreadsheet software', 'Financial analysis software', 'Office suite software', 'Desktop publishing software', 'Word processing software']
Hot Technologies
Hot Technology
N    20250
Y    11571
Name: count, dtype: int64
In Demand
In Demand
N    29396
Y     2425
Name: count, dtype: int64

In [32]:
onet

,O*NET-SOC Code,Title,Workplace Example,Element ID,Element Name,Hot Technology,In Demand
0,11-1011.00,Chief Executives,Adobe Acrobat,2.E.5.b,Document management software,Y,N
1,11-1011.00,Chief Executives,AdSense Tracker,2.E.6.f,Data base user interface and query software,N,N
2,11-1011.00,Chief Executives,Atlassian JIRA,2.E.5.a,Content workflow software,Y,N
3,11-1011.00,Chief Executives,Blackbaud The Raiser's Edge,2.E.6.c,Customer relationship management CRM software,N,N
4,11-1011.00,Chief Executives,ComputerEase construction accounting software,2.E.2.a,Accounting software,N,N
...,...,...,...,...,...,...,...
31816,53-7121.00,"Tank Car, Truck, and Ship Loaders",Linux,2.E.13.c,Operating system software,Y,N
31817,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Excel,2.E.4.i,Spreadsheet software,Y,N
31818,53-7121.00,"Tank Car, Truck, and Ship Loaders",Microsoft Office software,2.E.1.k,Office suite software,Y,N
31819,53-7121.00,"Tank Car, Truck, and Ship Loaders",SAP software,2.E.2.b,Enterprise resource planning ERP software,Y,N
31820,53-7121.00,"Tank Car, Truck, and Ship Loaders",Warehouse management system WMS,2.E.1.d,Materials requirements planning logistics and ...,N,Y

In [48]:
occupation_docs = (
                    onet.groupby(['O*NET-SOC Code', 'Title'])
                   .agg({
                       'Element Name': lambda x: list(x.unique()),
                       'Workplace Example': lambda x: list(x.unique()),
                       'Hot Technology': lambda x: list(x.unique()),
                       'In Demand': lambda x: list(x.unique())
                   })).reset_index()

In [49]:
occupation_docs

,O*NET-SOC Code,Title,Element Name,Workplace Example,Hot Technology,In Demand
0,11-1011.00,Chief Executives,"[Document management software, Data base user ...","[Adobe Acrobat, AdSense Tracker, Atlassian JIR...","[Y, N]","[N, Y]"
1,11-1011.03,Chief Sustainability Officers,"[Document management software, Graphics or pho...","[Adobe Acrobat, Adobe Photoshop, Email softwar...","[Y, N]","[N, Y]"
2,11-1021.00,General and Operations Managers,[Customer relationship management CRM software...,"[Act!, ActionWare, Adobe Acrobat, Adobe Creati...","[N, Y]","[N, Y]"
3,11-1031.00,Legislators,"[Document management software, Desktop publish...","[Adobe Acrobat, Adobe FrameMaker, Antenna Hous...","[Y, N]",[N]
4,11-2011.00,Advertising and Promotions Managers,[Business intelligence and data analysis softw...,"[Actuate BIRT, Adobe Acrobat, Adobe Acrobat Re...","[N, Y]","[N, Y]"
...,...,...,...,...,...,...
918,53-7071.00,Gas Compressor and Gas Pumping Station Operators,"[Facilities management software, Spreadsheet s...",[Computerized maintenance management system CM...,"[N, Y]",[N]
919,53-7072.00,"Pump Operators, Except Wellhead Pumpers","[Facilities management software, Spreadsheet s...",[Computerized maintenance management system CM...,"[N, Y]","[N, Y]"
920,53-7073.00,Wellhead Pumpers,"[Spreadsheet software, Office suite software, ...","[Microsoft Excel, Microsoft Office software, M...","[Y, N]",[N]
921,53-7081.00,Refuse and Recyclable Material Collectors,"[Analytical or scientific software, Facilities...","[AMCS Platform, Computerized maintenance manag...",[N],[N]
922,53-7121.00,"Tank Car, Truck, and Ship Loaders","[Data base user interface and query software, ...","[CompuWeigh GMS, Distributed control system DC...","[N, Y]","[N, Y]"

In [59]:
def create_document(row):
    skills = row["Element Name"]
    workplace_examples = row["Workplace Example"]
    hot_technology = row["Hot Technology"]
    in_demand = row["In Demand"]

    document = f"""
Occupation: {row["Title"]}
O*NET-SOC Code: {row["O*NET-SOC Code"]}

Software Skills:
{skills}

Workplace Examples:
{workplace_examples}

Hot Technology:
{hot_technology}

In Demand:
{in_demand}
"""

    return document.strip()


occupation_docs["document"] = occupation_docs.apply(
    create_document,
    axis=1
)

print("Number of documents:", len(occupation_docs))
print(occupation_docs["document"].iloc[0])

Number of documents: 923
Occupation: Chief Executives
O*NET-SOC Code: 11-1011.00

Software Skills:
['Document management software', 'Data base user interface and query software', 'Content workflow software', 'Customer relationship management CRM software', 'Accounting software', 'Data base reporting software', 'Electronic mail software', 'Time accounting software', 'Enterprise application integration software', 'Graphics or photo imaging software', 'Human resources software', 'Project management software', 'Analytical or scientific software', 'Presentation software', 'Enterprise resource planning ERP software', 'Spreadsheet software', 'Financial analysis software', 'Office suite software', 'Desktop publishing software', 'Word processing software', 'Web platform development software', 'Data base management system software', 'Internet browser software']

Workplace Examples:
['Adobe Acrobat', 'AdSense Tracker', 'Atlassian JIRA', "Blackbaud The Raiser's Edge", 'ComputerEase construction accounting software', 'Database reporting software', 'Databox', 'Email software', 'Exact Software Macola ES Labor Performance', 'Extensible markup language XML', 'Fund accounting software', 'Graphic presentation software', 'Halogen e360', 'Halogen ePraisal', 'HCSS HeavyBid', 'HCSS HeavyJob', 'Human resource information system (HRIS)', 'Infor SSA Human Capital Management', 'Intuit QuickBooks', 'Listserv software', 'Lyris HQ Web-Analytics Solution', 'Mentimeter', 'Microsoft Access', 'Microsoft Dynamics', 'Microsoft Dynamics AX', 'Microsoft Dynamics GP', 'Microsoft Excel', 'Microsoft FRx', 'Microsoft Office software', 'Microsoft Outlook', 'Microsoft PowerPoint', 'Microsoft Project', 'Microsoft Publisher', 'Microsoft SharePoint', 'Microsoft Word', 'Nedstat Sitestat', 'Norchard Solutions Succession Wizard', 'Online advertising reporting software', 'Oracle E-Business Suite', 'Oracle PeopleSoft', 'Oracle Siebel Server Sync', 'PHP', 'Relational database management software', 'Sage 50 Accounting', 'SAP software', 'SmugMug Flickr', 'Structured query language SQL', 'Web browser software']

Hot Technology:
['Y', 'N']

In Demand:
['N', 'Y']